/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as FavouritesRouteImport } from './routes/favourites'
import { Route as GenresRouteImport } from './routes/genres'
import { Route as MoviesRouteImport } from './routes/movies'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SeriesRouteImport } from './routes/series'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as WatchedRouteImport } from './routes/watched'
import { Route as WatchlistRouteImport } from './routes/watchlist'
import { Route as TitleIdRouteImport } from './routes/title.$id'
import { Route as MediaTypeTmdbIdRouteImport } from './routes/media.$type.$tmdbId'
import { Route as ApiPublicCronTmdbSyncRouteImport } from './routes/api/public/cron/tmdb-sync'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const FavouritesRoute = FavouritesRouteImport.update({
  id: '/favourites',
  path: '/favourites',
  getParentRoute: () => rootRouteImport,
} as any)
const GenresRoute = GenresRouteImport.update({
  id: '/genres',
  path: '/genres',
  getParentRoute: () => rootRouteImport,
} as any)
const MoviesRoute = MoviesRouteImport.update({
  id: '/movies',
  path: '/movies',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SeriesRoute = SeriesRouteImport.update({
  id: '/series',
  path: '/series',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchedRoute = WatchedRouteImport.update({
  id: '/watched',
  path: '/watched',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchlistRoute = WatchlistRouteImport.update({
  id: '/watchlist',
  path: '/watchlist',
  getParentRoute: () => rootRouteImport,
} as any)
const TitleIdRoute = TitleIdRouteImport.update({
  id: '/title/$id',
  path: '/title/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaTypeTmdbIdRoute = MediaTypeTmdbIdRouteImport.update({
  id: '/media/$type/$tmdbId',
  path: '/media/$type/$tmdbId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronTmdbSyncRoute = ApiPublicCronTmdbSyncRouteImport.update({
  id: '/api/public/cron/tmdb-sync',
  path: '/api/public/cron/tmdb-sync',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/auth': typeof AuthRoute
  '/discover': typeof DiscoverRoute
  '/favourites': typeof FavouritesRoute
  '/genres': typeof GenresRoute
  '/movies': typeof MoviesRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/series': typeof SeriesRoute
  '/settings': typeof SettingsRoute
  '/watched': typeof WatchedRoute
  '/watchlist': typeof WatchlistRoute
  '/title/$id': typeof TitleIdRoute
  '/media/$type/$tmdbId': typeof MediaTypeTmdbIdRoute
  '/api/public/cron/tmdb-sync': typeof ApiPublicCronTmdbSyncRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/auth': typeof AuthRoute
  '/discover': typeof DiscoverRoute
  '/favourites': typeof FavouritesRoute
  '/genres': typeof GenresRoute
  '/movies': typeof MoviesRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/series': typeof SeriesRoute
  '/settings': typeof SettingsRoute
  '/watched': typeof WatchedRoute
  '/watchlist': typeof WatchlistRoute
  '/title/$id': typeof TitleIdRoute
  '/media/$type/$tmdbId': typeof MediaTypeTmdbIdRoute
  '/api/public/cron/tmdb-sync': typeof ApiPublicCronTmdbSyncRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/auth': typeof AuthRoute
  '/discover': typeof DiscoverRoute
  '/favourites': typeof FavouritesRoute
  '/genres': typeof GenresRoute
  '/movies': typeof MoviesRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/series': typeof SeriesRoute
  '/settings': typeof SettingsRoute
  '/watched': typeof WatchedRoute
  '/watchlist': typeof WatchlistRoute
  '/title/$id': typeof TitleIdRoute
  '/media/$type/$tmdbId': typeof MediaTypeTmdbIdRoute
  '/api/public/cron/tmdb-sync': typeof ApiPublicCronTmdbSyncRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assistant'
    | '/auth'
    | '/discover'
    | '/favourites'
    | '/genres'
    | '/movies'
    | '/profile'
    | '/search'
    | '/series'
    | '/settings'
    | '/watched'
    | '/watchlist'
    | '/title/$id'
    | '/media/$type/$tmdbId'
    | '/api/public/cron/tmdb-sync'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assistant'
    | '/auth'
    | '/discover'
    | '/favourites'
    | '/genres'
    | '/movies'
    | '/profile'
    | '/search'
    | '/series'
    | '/settings'
    | '/watched'
    | '/watchlist'
    | '/title/$id'
    | '/media/$type/$tmdbId'
    | '/api/public/cron/tmdb-sync'
  id:
    | '__root__'
    | '/'
    | '/assistant'
    | '/auth'
    | '/discover'
    | '/favourites'
    | '/genres'
    | '/movies'
    | '/profile'
    | '/search'
    | '/series'
    | '/settings'
    | '/watched'
    | '/watchlist'
    | '/title/$id'
    | '/media/$type/$tmdbId'
    | '/api/public/cron/tmdb-sync'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssistantRoute: typeof AssistantRoute
  AuthRoute: typeof AuthRoute
  DiscoverRoute: typeof DiscoverRoute
  FavouritesRoute: typeof FavouritesRoute
  GenresRoute: typeof GenresRoute
  MoviesRoute: typeof MoviesRoute
  ProfileRoute: typeof ProfileRoute
  SearchRoute: typeof SearchRoute
  SeriesRoute: typeof SeriesRoute
  SettingsRoute: typeof SettingsRoute
  WatchedRoute: typeof WatchedRoute
  WatchlistRoute: typeof WatchlistRoute
  TitleIdRoute: typeof TitleIdRoute
  MediaTypeTmdbIdRoute: typeof MediaTypeTmdbIdRoute
  ApiPublicCronTmdbSyncRoute: typeof ApiPublicCronTmdbSyncRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favourites': {
      id: '/favourites'
      path: '/favourites'
      fullPath: '/favourites'
      preLoaderRoute: typeof FavouritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/genres': {
      id: '/genres'
      path: '/genres'
      fullPath: '/genres'
      preLoaderRoute: typeof GenresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movies': {
      id: '/movies'
      path: '/movies'
      fullPath: '/movies'
      preLoaderRoute: typeof MoviesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/series': {
      id: '/series'
      path: '/series'
      fullPath: '/series'
      preLoaderRoute: typeof SeriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watched': {
      id: '/watched'
      path: '/watched'
      fullPath: '/watched'
      preLoaderRoute: typeof WatchedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watchlist': {
      id: '/watchlist'
      path: '/watchlist'
      fullPath: '/watchlist'
      preLoaderRoute: typeof WatchlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/title/$id': {
      id: '/title/$id'
      path: '/title/$id'
      fullPath: '/title/$id'
      preLoaderRoute: typeof TitleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media/$type/$tmdbId': {
      id: '/media/$type/$tmdbId'
      path: '/media/$type/$tmdbId'
      fullPath: '/media/$type/$tmdbId'
      preLoaderRoute: typeof MediaTypeTmdbIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/tmdb-sync': {
      id: '/api/public/cron/tmdb-sync'
      path: '/api/public/cron/tmdb-sync'
      fullPath: '/api/public/cron/tmdb-sync'
      preLoaderRoute: typeof ApiPublicCronTmdbSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssistantRoute: AssistantRoute,
  AuthRoute: AuthRoute,
  DiscoverRoute: DiscoverRoute,
  FavouritesRoute: FavouritesRoute,
  GenresRoute: GenresRoute,
  MoviesRoute: MoviesRoute,
  ProfileRoute: ProfileRoute,
  SearchRoute: SearchRoute,
  SeriesRoute: SeriesRoute,
  SettingsRoute: SettingsRoute,
  WatchedRoute: WatchedRoute,
  WatchlistRoute: WatchlistRoute,
  TitleIdRoute: TitleIdRoute,
  MediaTypeTmdbIdRoute: MediaTypeTmdbIdRoute,
  ApiPublicCronTmdbSyncRoute: ApiPublicCronTmdbSyncRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
