/**
 * AUTO-GENERATED by scripts/enrich-tmdb.mjs — do not edit by hand.
 * Every field for a title comes from a single verified TMDB record, so a
 * poster/trailer/cast can never belong to a different film.
 */
import type { TmdbRecord } from "./tmdb-types";

export const TMDB: Record<string, TmdbRecord> = {};
